title: Sharvari Deshmukh
description: Site under construction!
email: sharvarisd18@gmail.com
logo: "/assets/profile_photo.jpg"
description: Interested to work in the areas of image processing, computer vision and deep-learning.
baseurl: ""
url: ""
github_username:  186shades
show_downloads: false
cv_path: "/assets/Sharvari_Deshmukh_SP24_Resume.pdf"

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      excerpt_separator: "<!--more-->"